kind = "web"
previewPath = "/"
title = "Town Pizza-Hut"
version = "1.0.0"
id = "artifacts/town-pizza-hut"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 25613

[services.development]
run = "pnpm --filter @workspace/town-pizza-hut run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/town-pizza-hut", "run", "build" ]
publicDir = "artifacts/town-pizza-hut/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "25613"
BASE_PATH = "/"
